spring:
  datasource:
    url: jdbc:mysql://47.99.116.208:3306/insurance?serverTimezone=Asia/Shanghai
    username: insurance
    password: crRhSzmJms7dnPbE
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: cn.wghtstudio.insurance.dao.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

ocr:
  apiKey: 6v7zqa2sHU1B5fHObGDQiGi3
  secretKey: 8vi1ZOopPZZUEsDV9BONFex57M5V7B9g

token:
  expireDate: 10800000
  secret: InsuranceBack