spring:
  datasource:
    url: jdbc:mysql://47.99.116.208:3306/insuranceDev?serverTimezone=Asia/Shanghai
    username: insuranceDev
    password: AFEtt55BN5fb8JHj
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: cn.wghtstudio.insurance.dao.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    web: debug
    cn:
      wghtstudio:
        insurance:
          dao:
            repository: debug

token:
  expireDate: 10800000
  secret: InsuranceBack

ocr:
  apiKey: tBjGONPBGD68WLEQL5iOWcCM
  secretKey: gmlsWtjTUDKh4AY2zpHpZGEvRMKeWSsZ

aliyun:
  accessKeyID: LTAI5tRKpksmrwZiJuzQSJqj
  accessKeySecret: EZn3nwVUOV1yo0mNUeBR4BaIUJ8SCU
  arn: acs:ram::1958639701172800:role/ramosstest
